<?php

namespace Scribe\MantleBundle\Doctrine\Repository\Route;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRedirectRepository extends EntityRepository
{
}

/* EOF */
