<?php

/*
 * This file is part of the Scribe Mantle Bundle.
 *
 * (c) Scribe Inc. <source@scribe.software>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Scribe\MantleBundle\Doctrine\Entity\Navigation;

use Scribe\Doctrine\Base\Entity\AbstractEntity;
use Scribe\Doctrine\Base\Model\HasAliases;
use Scribe\Doctrine\Base\Model\HasAttributes;
use Scribe\Doctrine\Base\Model\HasDescription;
use Scribe\Doctrine\Base\Model\HasName;
use Scribe\Doctrine\Behavior\Model\Sluggable\SluggableBehaviorTrait;
use Scribe\Doctrine\Exception\ORMExceptionInterface;
use Scribe\Doctrine\Exception\SubscriberEventORMException;

/**
 * Class Navigation.
 */
class Navigation extends AbstractEntity
{
    use HasAliases,
        HasName,
        HasDescription,
        HasAttributes,
        SluggableBehaviorTrait;

    /**
     * Support casting to string.
     *
     * @return string
     */
    public function __toString()
    {
        return (string) (__CLASS__.':'.$this->getId());
    }

    /**
     * This entity must not have auto-generated slugs.
     *
     * @throws SubscriberEventORMException
     */
    public function getAutoSlugFields()
    {
        throw new SubscriberEventORMException(
            'This entity does not support automatically generating slugs!',
            ORMExceptionInterface::CODE_GENERIC_FROM_MANTLE_BDL
        );
    }

    /**
     * Disable auto-generated slugs.
     *
     * @return bool
     */
    public function isSlugAutoGenerated()
    {
        return false;
    }
}

/* EOF */
