<?php

/*
 * This file is part of the Scribe Mantle Bundle.
 *
 * (c) Scribe Inc. <source@scribe.software>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Scribe\MantleBundle\Doctrine\Entity\Navigation;

use Scribe\Doctrine\Base\Entity\AbstractEntity;
use Scribe\Doctrine\Base\Model\HasAttributes;
use Scribe\Doctrine\Base\Model\HasChildrenInverseSide;
use Scribe\Doctrine\Base\Model\HasDescription;
use Scribe\Doctrine\Base\Model\HasName;
use Scribe\Doctrine\Behavior\Model\Sluggable\SluggableBehaviorTrait;

/**
 * Class NavigationSet.
 */
class NavigationSet extends AbstractEntity
{
    use HasName,
        HasDescription,
        HasAttributes,
        HasChildrenInverseSide,
        SluggableBehaviorTrait;

    /**
     * Support casting to string.
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getSlug();
    }

    /**
     * Fallback for auto slug creation if one is not explicitly set.
     *
     * @return array
     */
    public function getAutoSlugFields()
    {
        return [
            'name',
        ];
    }

    /**
     * Disable auto-generated slugs.
     *
     * @return bool
     */
    public function isSlugAutoGenerated()
    {
        return false;
    }
}

/* EOF */
