<?php

namespace Scribe\SharedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavMenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconTemplateRepository extends EntityRepository
{
    /**
     * @param  IconFamily    $family
     * @return IconTemplate 
     */
    public function loadHighestPriorityByFamily(IconFamily $family)
    {
        $q = $this
          ->createQueryBuilder('t')
          ->where('t.family = :family')
          ->setParameter('family', $family)
          ->orderBy('t.priority', 'DESC')
          ->setMaxResults(1)
          ->getQuery()
        ;

        try {
            return $q->getResult();
        }
        catch(NonUniqueResultException $e) {
            return null;
        }
    }

    /**
     * @param  string        $iconTemplateSlug
     * @return IconTemplate 
     */
    public function loadIconTemplateBySlug($iconTemplateSlug)
    {
        $q = $this
          ->createQueryBuilder('i')
          ->where('i.slug = :slug')
          ->setParameter('slug', $iconTemplateSlug)
          ->setMaxResults(1)
          ->getQuery()
        ;

        try {
            return $q->getSingleResult();
        }
        catch(\Exception $e) {
            throw $e;
        }
    }
}
