<?php

namespace Scribe\SharedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterUserRepository extends EntityRepository
{
}
