api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make : ~
env_prep : get-composer,db-config
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary,memcached,yaml
app_prep : dep-composer,db-create-mantle,db-load
app_post : db-unload
app_path : bin/mantle
pkg_name : mantle-bundle
pkg_desc : "bundle used primarily by Scribe Inc for their own website and client sites. It includes the collection of packages required for our development needs."
pkg_bndl : true
