<?php

namespace Scribe\MantleBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * NavMenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconFamilyRepository extends EntityRepository
{
    /**
     * @param  string        $iconSlug
     * @return IconTemplate 
     */
    public function loadIconFamilyBySlug($iconFamilySlug)
    {
        $q = $this
          ->createQueryBuilder('i')
          ->where('i.slug = :slug')
          ->setParameter('slug', $iconFamilySlug)
          ->setMaxResults(1)
          ->getQuery()
        ;

        try {
            return $q->getSingleResult();
        }
        catch(\Exception $e) {
            throw $e;
        }
    }
}
