<?php

namespace Scribe\MantleBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * NavMenuSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavMenuSettingRepository extends EntityRepository
{
}

/* EOF */
