<?php

namespace Scribe\MantleBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * NavMenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavMenuItemRepository extends EntityRepository
{
    /**
     * @param $id
     * @param string|null $context
     * @return mixed|null
     */
    public function findByContextOrderByWeight($context)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.context LIKE :context')
            ->setParameter('context', $context)
            ->orderBy('e.weight')
            ->getQuery()
        ;

        try {
            $entries = $q->getResult();
        }
        catch(NoResultException $e) {
            return null;
        }

        return $entries;
    }

    /**
     * @param $id
     * @param null|string $contextBundle
     * @param null|string $contextController
     * @param null|string $contextAction
     * @return mixed|null
     */
    public function findByContextFullOrderByWeight($contextBundle, $contextController, $contextAction)
    {
        $q = $this
            ->createQueryBuilder('e')
            ->where('e.context LIKE :contextBundle')
            ->orWhere('e.context LIKE :contextController')
            ->orWhere('e.context LIKE :contextAction')
            ->setParameter('contextBundle', $contextBundle)
            ->setParameter('contextController', $contextController)
            ->setParameter('contextAction', $contextAction)
            ->orderBy('e.weight')
            ->getQuery()
        ;

        try {
            $entries = $q->getResult();
        }
        catch(NoResultException $e) {
            return null;
        }

        return $entries;
    }
}

/* EOF */
