<?php
/*
 * This file is part of the Scribe Mantle Bundle.
 *
 * (c) Scribe Inc. <source@scribe.software>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Scribe\MantleBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;
use Scribe\MantleBundle\Entity\NodeRenderEngine;

/**
 * NodeRenderEngineRepository
 * @package Scribe\MantleBundle\EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRenderEngineRepository extends EntityRepository
{
}
