<?php

namespace Scribe\MantleBundle\EntityRepository;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectsRepository extends EntityRepository
{
}

/* EOF */
