<?php

namespace Scribe\SharedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseSearchReplaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseSearchReplaceRepository extends EntityRepository
{
}
