scribe_search:
    pattern:  /_search
    defaults: { _controller: ScribeSharedBundle:Search:Query }

scribe_contact:
    pattern:  /contact
    defaults: { _controller: ScribeSharedBundle:Contact:Index }