Scribe\MantleBundle\Entity\AssetDescriptor:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\EntityRepository\AssetDescriptorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        binContent:
            type: blob
            nullable: true
        markup:
            type: text
            nullable: true
        height:
            type: integer
            nullable: true
        width:
            type: integer
            nullable: true
    oneToMany:
        assets:
            targetEntity: Scribe\MantleBundle\Entity\Asset
            mappedBy: assetDescriptor
    lifecycleCallbacks: {  }
