Scribe\MantleBundle\Entity\AssetType:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\AssetTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        element:
            type: string
            length: 255
        attributes:
            type: json_array
    oneToMany:
        assets:
            targetEntity: Scribe\MantleBundle\Entity\Asset
            mappedBy: assetType
    lifecycleCallbacks: {  }
