Scribe\MantleBundle\Entity\AssetDescriptor:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\AssetDescriptorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        binContent:
            type: blob
        markup:
            type: text
        height:
            type: integer
        width:
            type: integer
    lifecycleCallbacks: {  }
