---

Scribe\MantleBundle\Doctrine\Entity\Content\Block:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Content_Block
    changeTrackingPolicy : DEFERRED_EXPLICIT
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Content\BlockRepository

    id :

        slug :
            type      : string
            length    : 128
            generator :
                strategy : NONE

    fields:

        title :
            type     : string
            length   : 512
            nullable : false

        description :
            type     : text
            nullable : true

        content :
            type     : text

        attributes:
            type     : json_array
            nullable : true

    manyToMany:

        assets:
            targetEntity : Asset
            mappedBy     : blocks

...
