Scribe\MantleBundle\Doctrine\Entity\Icon\Icon:

    type:            entity
    table:           MantleBundle_Icon
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Icon\IconRepository

    id:

        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO

    fields:

        slug:
            type:   string
            length: 40

        unicode:
            type:     string
            length:   10
            nullable: true

        name:
            type:   string
            length: 40

        aliases:
            type:     json_array
            nullable: true

        categories:
            type:     json_array
            nullable: true

        attributes:
            type:     json_array
            nullable: true

    manyToMany:

        families:
            targetEntity: IconFamily
            inversedBy:   icons
            joinTable:
                name: MantleBundle_Icon_MaptoFamilies
                joinColumns:
                    iconId:
                        referencedColummnName: id
                inverseJoinColumns:
                    iconFamilyId:
                        referencedColummnName: id
