Scribe\MantleBundle\Doctrine\Entity\Node\NodeContextType:

    type:            entity
    table:           null
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Node\NodeContextTypeRepository

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:

        name:
            type:   string
            length: 255

    oneToMany:

        nodes:
            targetEntity: Node
            mappedBy:     context
