Scribe\MantleBundle\Doctrine\Entity\Navigation\NavigationItem:

    type:            entity
    table:           MantleBundle_NavigationItem
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Navigation\NavigationItem

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    fields:

        title:
            type:     string
            length:   '510'
            nullable: false

        description:
            type:     text
            nullable: true
