---
Scribe\MantleBundle\Doctrine\Entity\Icon\IconTemplate:

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_Icon_Template
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Icon\IconTemplateRepository

    id:

        id:
            type      : integer
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    indexes:

        iconTemplateSlugIndex:
            columns: [ slug ]

    uniqueConstraints:

        iconTemplateSlugFamIndex:
            columns: [ slug, family ]

    fields:

        slug:
            type     : string
            length   : 512
            nullable : false

        description:
            type   : string
            length : 128

        engine:
            type   : string
            length : 10

        template:
            type : text

        priority:
            type : smallint

    manyToOne:

        family:
            targetEntity: IconFamily
            inversedBy  : templates
            joinColumn  :
                name             : family
                referencedColumn : id

...
