---
Scribe\MantleBundle\Doctrine\Entity\Locale\LanguageFamily:

    type            : entity
    charset         : utf8mb4
    collate         : utf8mb4_unicode_ci
    options         :
        row_format  : DYNAMIC
    table           : MantleBundle_LocaleLanguageFamily
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Locale\LanguageFamilyRepository

    id:

        id:
            type      : smallint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    uniqueConstraints:

        languageFamilySlug:
            columns: [ slug ]

    fields:

        slug:
            type   : string
            length : 128

        name:
            type   : string
            length : 256

        src:
            type     : string
            length   : 1024
            nullable : true

        description:
            type     : text
            nullable : true

    oneToMany:

        languageCollection:
            targetEntity : LanguageName
            mappedBy     : family
            fetch        : LAZY

...
