---
Scribe\MantleBundle\Doctrine\Entity\Locale\Country:

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_Locale_Country
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Locale\CountryRepository

    id:

        id:
            type      : integer
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    uniqueConstraints:

        countryCodeUnique:
            columns: [ code ]

        countryCode3Unique:
            columns: [ codeAlpha3 ]

        countrycodeNUnique:
            columns: [ codeNumeric ]

    fields:

        code:
            type   : string
            length : 2
            fixed  : true

        codeAlpha3:
            type   : string
            length : 3
            fixed  : true

        codeNumeric:
            type     : smallint

        name:
            type   : string
            length : 1024

        nameProper:
            type     : string
            length   : 1024
            nullable : true

...
