---
Scribe\MantleBundle\Doctrine\Entity\Locale\Country:

    type            : entity
    charset         : utf8mb4
    collate         : utf8mb4_unicode_ci
    options         :
        row_format  : DYNAMIC
    table           : MantleBundle_LocaleCountry
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Locale\CountryRepository

    id:

        id:
            type      : integer
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    uniqueConstraints:

        countryCodeUnique:
            columns: [ code ]

    fields:

        code:
            type   : string
            length : 2
            fixed  : true

        name:
            type   : string
            length : 1024
            fixed  : false

...
