---
Scribe\MantleBundle\Doctrine\Entity\Locale\Language:

    type:            entity
    charset:         utf8mb4
    collate:         utf8mb4_unicode_ci
    table:           MantleBundle_LocaleLanguage
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Locale\LanguageRepository

    id:

        id:
            type: integer
            id:   true
            generator:
                strategy: AUTO

    fields:

        name:
            type   : string
            length : 512

        code:
            type   : string
            length : 2
            fixed  : true

        nativeNames:
            type     : json_array
            nullable : true

        altNames:
            type     : json_array
            nullable : true

#    oneToMany:
##
#        family:
#            targetEntity : LanguageFamily
#            fetch        : EAGER
...
