---
Scribe\MantleBundle\Doctrine\Entity\Locale\Locale:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Local
    changeTrackingPolicy : DEFERRED_EXPLICIT
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Locale\LocaleRepository

    id:

        slug:
            type   : string
            length : 64
            id     : true
            generator :
                strategy: NONE

    manyToOne:

        language:
            targetEntity : LanguageName
            fetch        : EAGER
            joinColumn   :
                name                 : language
                referencedColumnName : slug

        country:
            targetEntity : Country
            fetch        : EAGER
            joinColumn   :
                name                 : country
                referencedColumnName : slug

...
