---
Scribe\MantleBundle\Doctrine\Entity\Meta\MetaTitle:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Meta_Title
    changeTrackingPolicy : DEFERRED_EXPLICIT
    readOnly             : true
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Meta\MetaTitleRepository

    id:

        id:
            type : integer
            id   : true
            generator :
                strategy : AUTO

    indexes :

        metaLocaleIndexed:
            columns: [ locale ]

        metaBundleIndexed:
            columns: [ bundle ]

        metaControllerIndexed:
            columns: [ controller ]

        metaActionIndexed:
            columns: [ action ]

    fields:

        title:
            type   : string
            length : 1024

    manyToOne:

        locale:
            targetEntity : Scribe\MantleBundle\Doctrine\Entity\Locale\Locale
            joinColumn   :
                name                 : locale
                referencedColumnName : slug

        bundle:
            targetEntity : Scribe\MantleBundle\Doctrine\Entity\State\RuntimeBundle
            joinColumn   :
                name                 : bundle
                referencedColumnName : slug

        controller:
            targetEntity : Scribe\MantleBundle\Doctrine\Entity\State\RuntimeController
            joinColumn   :
                name                 : controller
                referencedColumnName : slug

        action:
            targetEntity : Scribe\MantleBundle\Doctrine\Entity\State\RuntimeAction
            joinColumn   :
                name                 : action
                referencedColumnName : slug

...
