---
Scribe\MantleBundle\Doctrine\Entity\Navigation\NavigationSet:

    type            : entity
    charset         : utf8mb4
    collate         : utf8mb4_unicode_ci
    options         :
        row_format  : DYNAMIC
    table           : MantleBundle_NavigationSet
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Navigation\NavigationSetRepository

    id:

        id:
            type      : integer
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    fields:

        name:
            type     : string
            length   : 512
            nullable : false

        description:
            type     : text
            nullable : true

        attributes:
            type     : json_array
            nullable : false

    oneToMany:

        children:
            targetEntity : NavigationItem
            mappedBy     : root

...
