Scribe\MantleBundle\Entity\NavMenuSubItem:

    type:            entity
    table:           null
    repositoryClass: Scribe\MantleBundle\EntityRepository\NavMenuSubItemRepository

    fields:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

        title:
            type: string
            length: 40

        icon:
            type:     string
            length:   40
            nullable: true

        weight:
            type:     integer
            nullable: true

        header:
            type:     boolean
            nullable: true

        routeName:
            type:     string
            length:   85
            nullable: true

        routeParameters:
            type:     json_array
            nullable: true

        roleRestrictions:
            type:     json_array
            nullable: true

        reverseRoleRestrictions:
            type:     json_array
            nullable: true

        attrs:
            type:     json_array
            nullable: true

    manyToOne:

        parent:
            targetEntity: NavMenuItem
            inversedBy:   subItems
            joinColumn:
                name:                 parentId
                referencedColumnName: id

    lifecycleCallbacks: {  }
