Scribe\MantleBundle\Entity\NodeRevisionDiff:
    type: entity
    table: null
    repositoryClass: Scribe\MantleBundle\Entity\NodeRevisionDiffRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        diff:
            type: text
    oneToOne:
        nodeRevision:
            targetEntity: Scribe\MantleBundle\Entity\NodeRevision 
            inversedBy:  diff 
            joinColumn:
                name:            nodeRevisionId 
                referencedColumn: id
    lifecycleCallbacks: {  }
