---
Scribe\MantleBundle\Doctrine\Entity\Node\NodeRevisionDiff :

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_Node_RevisionDiff
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Node\NodeRevisionDiffRepository

    id :

        id:
            type      : bigint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    fields :

        diff :
            type : text

    oneToOne :

        nodeRevision :
            targetEntity : NodeRevision
            inversedBy   : diff
            joinColumn   :
                name             : nodeRevisionId
                referencedColumn : id

...
