Scribe\MantleBundle\Doctrine\Entity\Node\NodeRenderEngine:

    type:            entity
    charset:         utf8mb4
    collate:         utf8mb4_unicode_ci
    table:           MantleBundle_NodeRenderEngine
    repositoryClass: Scribe\MantleBundle\Doctrine\Repository\Node\NodeRenderEngineRepository

    id:

        id:
            type:      integer
            id:        true
            generator: { strategy: AUTO }

    oneToMany:

        revisions:
            targetEntity: NodeRevision
            mappedBy:     renderEngine
