---
Scribe\MantleBundle\Doctrine\Entity\Node\NodeRenderEngine:

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_Node_RenderEngine
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Node\NodeRenderEngineRepository

    id:

        id:
            type      : smallint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    oneToMany:

        revisions:
            targetEntity : NodeRevision
            mappedBy     : renderEngine

...
