---
Scribe\MantleBundle\Doctrine\Entity\State\RuntimeAction:

    type            : entity
    options         :
        row_format  : DYNAMIC
        charset     : utf8mb4
        collate     : utf8mb4_unicode_ci
    table           : Mantle_State_RuntimeAction
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\State\RuntimeActionRepository

    id:

        id:
            type      : smallint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    indexes :

        stateRtControllerIndex:
            columns: [ name ]

    fields:

        name:
            type   : string
            length : 512

        description:
            type     : text
            nullable : true

...
