---
Scribe\MantleBundle\Doctrine\Entity\Translation\TranslationMessage:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Translation_Message
    changeTrackingPolicy : DEFERRED_EXPLICIT
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Translation\TranslationMessageRepository

    id:

        uuid :
            type      : bin_uuid
            generator :
                strategy : CUSTOM
            customIdGenerator:
                class: Scribe\Doctrine\ORM\Id\BinaryUuid4PessimisticGenerator

    fields:

        value :
            type : text

    manyToOne:

        locale:
            targetEntity : Scribe\MantleBundle\Doctrine\Entity\Locale\Locale
            fetch        : EAGER
            joinColumn:
                name                 : locale
                referencedColumnName : slug

        translation:
            targetEntity : Translation
            inversedBy   : messageCollection
            fetch        : EAGER
            joinColumn   :
                name                 : translation
                referencedColumnName : slug

...
