---
Scribe\MantleBundle\Doctrine\Entity\Translation\Translation:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Translation
    changeTrackingPolicy : DEFERRED_EXPLICIT
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Translation\TranslationRepository

    id :

        slug:
            type   : string
            length : 64
            id     : true
            generator :
                strategy: NONE

    uniqueConstraints :

        translationSlugDomainUnique :
            columns : [ domain ]

    manyToOne :

        domain :
            targetEntity : TranslationDomain
            fetch        : EAGER
            joinColumn   :
                name                 : domain
                referencedColumnName : slug

    oneToMany :

        messageCollection :
            targetEntity : TranslationMessage
            mappedBy     : translation
            fetch        : EAGER

...
