---
Scribe\MantleBundle\Doctrine\Entity\Translation\Translation:

    type            : entity
    charset         : utf8mb4
    collate         : utf8mb4_unicode_ci
    options         :
        row_format  : DYNAMIC
    table           : MantleBundle_Translation
    repositoryClass : Scribe\MantleBundle\Doctrine\Repository\Translation\TranslationRepository

    id:

        id:
            type      : smallint
            id        : true
            options   :
                unsigned : true
            generator :
                strategy : AUTO

    uniqueConstraints:

        translationSlugDomainUnique:
            columns:
                - slug
                - domain

    fields:

        slug:
            type   : string
            length : 768

    manyToOne:

        domain:
            targetEntity : TranslationDomain
            fetch        : EAGER
            joinColumn   :
                name                 : domain
                referencedColumnName : id

    oneToMany:

        messageCollection:
            targetEntity : TranslationMessage
            mappedBy     : translation
            fetch        : EAGER

...
