---
Scribe\MantleBundle\Doctrine\Entity\Translation\TranslationDomain:

    type                 : entity
    options              :
        row_format       : DYNAMIC
        charset          : utf8mb4
        collate          : utf8mb4_unicode_ci
    table                : Mantle_Translation_Domain
    changeTrackingPolicy : DEFERRED_EXPLICIT
    repositoryClass      : Scribe\MantleBundle\Doctrine\Repository\Translation\TranslationDomainRepository

    id:

        slug:
            type   : string
            length : 64
            id     : true
            generator :
                strategy: NONE

    fields:

        description:
            type     : text
            nullable : true

...
